# --- FUENTES ---
font_family      JetBrainsMono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        12.0
disable_ligatures never

# --- VENTANA Y APARIENCIA ---
background_opacity 0.85
window_padding_width 10
hide_window_decorations yes
confirm_os_window_close 0

# --- TEMA NORDIC ---
foreground            #D8DEE9
background            #2E3440
selection_foreground  #000000
selection_background  #FFFACD
url_color             #0087BD
cursor                #81A1C1

# Colores de la terminal
color0  #3B4252
color8  #4C566A
color1  #BF616A
color9  #BF616A
color2  #A3BE8C
color10 #A3BE8C
color3  #EBCB8B
color11 #EBCB8B
color4  #81A1C1
color12 #81A1C1
color5  #B48EAD
color13 #B48EAD
color6  #88C0D0
color14 #88C0D0
color7  #E5E9F0
color15 #ECEFF4

# --- ATAJOS ÚTILES ---
map ctrl+c copy_or_interrupt
map ctrl+v paste_from_clipboard
map ctrl+shift+c copy_to_clipboard
map ctrl+shift+v paste_from_clipboard
